name: Install Hatch Action
description: Install and configure Hatch
branding:
  icon: download-cloud
  color: purple

inputs:
  version:
    description: The version of Hatch to install
    default: latest

runs:
  using: composite
  steps:
  - name: Install and configure Hatch
    # Command needs to be wrapped in single quotes so backslashes are preserved for Windows paths
    run: "'${{ github.action_path }}${{ runner.os == 'Windows' && '\\' || '/' }}main.sh'"
    shell: bash
    env:
      VERSION: ${{ inputs.version }}
