DEFAULT_BUILD_DIRECTORY = 'dist'


class BuildEnvVars:
    LOCATION = 'HATCH_BUILD_LOCATION'
    CLEAN = 'HATCH_BUILD_CLEAN'
    HOOKS_ONLY = 'HATCH_BUILD_HOOKS_ONLY'
    NO_HOOKS = 'HATCH_BUILD_NO_HOOKS'
