---
name: Hatch feature request
description: Suggest an idea for this project
labels: ["kind:feature"]
body:
  - type: markdown
    attributes:
      # yamllint disable rule:line-length
      value: "
        <img src='https://raw.githubusercontent.com/pypa/hatch/HEAD/docs/assets/images/logo.svg' align='left' width='80' height='80'>
        Thank you for finding the time to propose new feature!

        We really appreciate the community efforts to improve Hatch.

        Please keep feature requests to smaller incremental changes that do not make changes to the assumptions
        about hatch. 
        
        If unsure - open a [discussion](https://github.com/pypa/hatch/discussions) first to gather
        an initial feedback on your idea.

        <br clear='left'/>"

      # yamllint enable rule:line-length
  - type: textarea
    attributes:
      label: Description
      description: A short description of your feature
  - type: textarea
    attributes:
      label: Use case/motivation
      description: What would you like to happen?
      placeholder: >
          Rather than telling us how you might implement this feature, try to take a
          step back and describe what you are trying to achieve.
  - type: textarea
    attributes:
      label: Related issues
      description: Is there currently another issue associated with this?
  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        If want to submit a PR you do not need to open feature request, <b>just create the PR!</b>.
        Especially if you already have a good understanding of how to implement the feature.
        Hatch is a PyPA managed project but we love to bring new contributors in.
        Find us on the PyPA Discord Server under #hatch
        It's optional though - if you have good idea for small feature,
        others might implement it if they pick an interest in it, so feel free to leave that
        checkbox unchecked.
      options:
        - label: Yes I am willing to submit a PR!
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: The Code of Conduct helps create a safe space for everyone. We require
        that everyone agrees to it.
      options:
        - label: >
            I agree to follow the Python Software Foundation's
            [Code of Conduct](https://policies.python.org/python.org/code-of-conduct/)
          required: true
  - type: markdown
    attributes:
      value: "Thanks for completing our form!"