authors:
  ofek:
    name: Ofek Lev
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/9677399
  flying-sheep:
    name: Phil A.
    description: Contributor
    avatar: https://avatars.githubusercontent.com/u/291575
