authors:
  ofek:
    name: Ofek Lev
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/9677399
  flying-sheep:
    name: Phil A.
    description: Contributor
    avatar: https://avatars.githubusercontent.com/u/291575
  cjames23:
    name: Cary Hawkins
    description: Co-maintainer
    avatar: https://avatars.githubusercontent.com/u/8369962?v=4
