name: test install

on:
  push:
    branches:
    - install
  pull_request:
    branches:
    - install

jobs:
  run:
    name: Install ${{ matrix.job.target }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-22.04
        - target: x86_64-pc-windows-msvc
          os: windows-2022
        - target: aarch64-apple-darwin
          os: macos-14
        - target: x86_64-apple-darwin
          os: macos-12

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install
      # Command needs to be wrapped in single quotes so backslashes are preserved for Windows paths
      run: "'${{ github.workspace }}${{ runner.os == 'Windows' && '\\' || '/' }}main.sh'"
      shell: bash
      env:
        VERSION: latest

    - name: Verify
      run: hatch --version
